# Start external programs

[[startProcess]]
command = "pkill nimdow"
keys = [ "Delete" ]
modifiers = [ "control", "alt" ]

[[startProcess]]
command = "$BROWSER"
keys = [ "i" ]
modifiers = [ "super" ]

[[startProcess]]
command = "dmenu_run"
keys = [ "p" ]
modifiers = [ "super" ]

[[startProcess]]
command = "st"
keys = [ "Return" ]
modifiers = [ "super" ]

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  #"firefox",
  #"st",
]

[settings]
  # Window settings
  gapSize = 12
  borderWidth = 1
  borderColorUnfocused = "#282a36"
  borderColorFocused = "#50fa7b"
  borderColorUrgent = "#ff5555"
  # Bar settings
  barHeight = 20
  barBackgroundColor = "#282a36"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#50fa7b"
  barUrgentColor = "#ff5555"
  barFonts = [
    "monospace:size=10:anialias=false",
    "NotoColorEmoji:size=10:anialias=false"
  ]
  # General settings
  loggingEnabled = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super", "shift" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

# Controls that use keys that reference tags.
[tagcontrols]

  [tagcontrols.goToTag]
  modifiers = [ "super" ]

  # [tagcontrols.moveWindowToTag]
  # modifiers = [ "super", "shift" ]

  # [tagcontrols.toggleTagView]
  # modifiers = [ "super", "control" ]

  # [tagcontrols.toggleWindowTag]
  # modifiers = [ "super", "shift", "control" ]

# Tag configurations.
[tags]

  [tags.1]
  displayString = "code"
  key = "parenleft"
  modifiers = [ "shift" ]

  [tags.2]
  key = "parenright"
  displayString = "two"
  modifiers = [ "shift" ]

  [tags.3]
  key = "bracketright"
  displayString = "3"
  modifiers = [ "shift" ]

  [tags.4]
  key = "plus"
  displayString = "4"
  modifiers = [ "shift" ]

  [tags.5]
  key = "bracketleft"
  displayString = "5"
  modifiers = [ "shift" ]

  [tags.6]
  key = "braceright"
  displayString = "6"

  [tags.7]
  key = "braceleft"
  displayString = "7"

  [tags.8]
  key = "exclam"
  displayString = "8"
  modifiers = [ "shift" ]

  [tags.9]
  key = "equal"
  displayString = "9"

